import type { Metadata } from 'next'
import { jose, unna } from '@/app/fonts'
import './globals.css'
import { unstable_setRequestLocale } from 'next-intl/server'
import { Suspense } from 'react'
import HeaderWrapper from '@/components/header/HeaderWrapper'
import Footer from '@/components/footer/Footer'
import Loading from '@/components/Loading'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

// Can be imported from a shared config
const locales = ['ro', 'en']

export function generateStaticParams() {
	return locales.map((locale) => ({ locale }))
}

export default function LocaleLayout({
	children,
	params: { locale },
}: {
	children: React.ReactNode
	params: { locale: string }
}) {
	unstable_setRequestLocale(locale)
	return (
		<html
			lang={locale}
			className={`${jose.variable} ${unna.variable}`}
		>
			<body className="relative pt-16 xl:pt-24 pb-[85px] xl:pb-[280px]">
				<Suspense fallback={<Loading />}>
					<HeaderWrapper />
					<main className="">{children}</main>
					<Footer />
				</Suspense>
			</body>
		</html>
	)
}
