import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { unstable_setRequestLocale } from 'next-intl/server'
import { Suspense } from 'react'
import HeaderWrapper from '@/components/header/HeaderWrapper'
import Footer from '@/components/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

// Can be imported from a shared config
const locales = ['ro', 'en']

export function generateStaticParams() {
	return locales.map((locale) => ({ locale }))
}

export default function LocaleLayout({
	children,
	params: { locale },
}: {
	children: React.ReactNode
	params: { locale: string }
}) {
	unstable_setRequestLocale(locale)
	return (
		<html lang={locale}>
			<body className="relative pt-16 xl:pt-24 pb-[76px] xl:pb-[300px]">
				<Suspense fallback="Loading...">
					<HeaderWrapper />
					<main className="pt-8 xl:pt-20 pb-16 xl:pb-32">
						{children}
					</main>
					<Footer />
				</Suspense>
			</body>
		</html>
	)
}
